package com.myspace.gitproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class contactDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "number")
	private java.lang.String number;

	public contactDetails() {
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public contactDetails(java.lang.String number) {
		this.number = number;
	}

}